[package]
name = "component_util"
version = "0.1.0"
edition.workspace = true

[dependencies]
feature_str_from_raw_parts_util = { workspace = true, optional = true }

[features]
default = ["feature_str_from_raw_parts_util"]
feature_str_from_raw_parts_util = ["dep:feature_str_from_raw_parts_util"]
